#+date: <2020-02-09 Sun>
#+title: 关于
#+description: 关于小虫飞飞大本营内容和背景的简单介绍
#+type: about


* 主要内容
  =小虫飞飞大本营= 以 _技术_ 为主要话题，将笔者在日常工作、无聊闲逛中遇到的有趣内容整理出来。一方面帮助自己归纳总结，一方面期待给更多朋友带来有益的思考。内容主要包含以下几类：
  - 编程语言。当前主流语言如： =jvm系= , =C/C++= , =C#= , =Python= , =Golang= 等；也包含一些小众但在具体领域有专长的语言，比如： =Lisp= , =R= 等。
  - 分布式系统。包含架构设计，组件应用，网络底层通信，服务治理，CAP 问题解决等。
  - 大数据处理。海量数据离线、实时计算的解决方案，具体结合 =spark/storm/flink= 介绍底层原理和实际应用。
  - 机器学习和推荐系统。网络中关于基础算法和内容有丰富资源， =小虫= 会侧重于实际问题的思路和解决方案。
  - 工具。大家看博客，撸代码都是为了增长学识和能力。除了专业技能自身，学习的方法、使用的工具也很重要。 =小虫= 会将业界反馈良好的利器分享出来，结合具体场景描述利弊。

* 关于小虫
  也许有人好奇，技术死宅为什么会起一个 =小虫飞飞= 的称号，故意卖萌吗？对啊，彪形大汉内心不能是一个小白兔吗？其实。。。。。。。。。。真的不是这样的。 =小虫= 主要还是来自年幼时两段深刻的记忆：

- 《水浒传》。特别是武松打虎这一段，其中关于老虎描述是：云生从龙，风生从虎。龙嘛比较虚幻，虎则是切实存在的兽中之王。因此特别想 /"狐假虎威"/ ，不过还是要含蓄点，所以取名众梁山好汉口中的： *大虫* 。
- 一部动画片的主题曲：有一只小蜜峰，飞到西呀飞到东，嗡嗡嗡嗡，嗡嗡嗡嗡，不怕雨也不怕风。很朴实简单，但却塑造了一个勇敢、不畏艰险的英雄形象。这时我才知道，身形的大小不重要，关键在：态度和坚持。


  技术本来就艰深复杂，但同样充满乐趣。大家几乎都有过被bug 折腾得死去活来的惨痛经历，那种百思不得其解的体验就像是丛林中迷途的蚂蚁。但总有柳暗花明的时候，也许一个转瞬即逝的小想法就像萤火虫给黑暗的旅途带来光明，令人豁然开朗。这种舒爽相必也是大家负重前行的动力之一吧。

  总之，希望 =小虫= 能伴您一起在技术丛林中探险，也许 99% 的过程都很枯燥乏味，但只要有那1% 的收获也就不负此行了吧。
